config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  # login URL
  get 'auth/github', as: :github_auth

  # Populate list of available repository
  resources :repositories, only: %i[index show] do
    member do
      get 'repo_commits', defaults: { format: 'json' }
    end
  end

  # Manage user session
  match 'auth/:provider/callback', to: 'sessions#create', via: %i[post get]
  delete 'sessions/destroy', as: :logout
end

app/models/application_record.rb
# frozen_string_literal: true

# Application Record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/format_json.rb
# frozen_string_literal: true

# Format JSON data
module FormatJson
  extend ActiveSupport::Concern

  # self methods of models
  module ClassMethods
    # map required commits data
    def format_commits(response)
      response.map do |c|
        {
          committer_date: c['commit']['committer']['date'],
          committer_name: c['commit']['committer']['name'],
          commit_message: c['commit']['message']
        }
      end
    end

    # map required repositories data
    def format_repositories(response)
      response.map do |r|
        {
          name: r['name'],
          open_issues: r['open_issues'],
          stargazers_count: r['stargazers_count'],
          forks: r['forks'],
          private: r['private']
        }
      end
    end

    # get required repository data
    def format_repository(response)
      {
        name: response['name'],
        description: response['description']
      }
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

# User model for save users data
class User < ApplicationRecord
  # include concerns for format response data
  include FormatJson

  def self.find_or_create_from_auth_hash(auth_hash)
    @user = User.find_or_create_by(
      provider: auth_hash[:provider],
      uid: auth_hash[:uid]
    )
    @user.update(
      name: auth_hash[:info][:nickname],
      avatar_url: auth_hash[:info][:image],
      token: auth_hash[:credentials][:token]
    )
    @user
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application page controller
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def authenticate_user
    # rubocop:disable LineLength
    redirect_to :root, alert: 'Please login with github account.' unless logged_in?
    # rubocop:enable LineLength
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Home page controller
class HomeController < ApplicationController
  def index
    redirect_to repositories_path if logged_in?
  end
end

app/controllers/repositories_controller.rb
# frozen_string_literal: true

# Use for fetch github data
class RepositoriesController < ApplicationController
  before_action :authenticate_user

  def index
    # Call service for get all repositories
    response = GithubApi.new(user: current_user)
    @repositories = response.repositories
  end

  def show
    # Set Date range for commits history
    @since_date = (Time.now - 5.day).beginning_of_day
    @until_date = Time.now
    # Call service for get repository detail
    response = GithubApi.new(user: current_user, repo_name: params[:id])
    @repo = response.repository
    redirect_to repositories_path, alert: 'Repo not found.' if @repo.nil?
  end

  def repo_commits
    @since_date = params[:since_date].to_date.beginning_of_day
    @until_date = params[:until_date].to_date.end_of_day
    # Call service for get repository commits history
    response = GithubApi.new(user: current_user, repo_name: params[:id],
                             since_date: @since_date, until_date: @until_date)
    @commits = response.repo_commits
    render json: @commits
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# Use for authentication with github
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = @user.id
    redirect_to repositories_path, notice: 'Logged in successfully'
  rescue StandardError => e
    redirect_to root_path, alert: e.message
  end

  def destroy
    reset_session
    redirect_to :root
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Helper methods for application controller
module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# Helper methods for home controller
module HomeHelper
end

app/helpers/repositories_helper.rb
# frozen_string_literal: true

# Helper methods for repositories controller
module RepositoriesHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

# Helper methods for session controller
module SessionsHelper
end

app/views/home/index.html.erb
<div class="row login-card">
	<div class="col-sm-12 col-md-9 mx-auto text-center">
		<%= image_tag 'amura.png' %>
		<%= link_to github_auth_path, class: "btn btn-lg btn-primary btn-block text-uppercase" do %>
			<i class="fa fa-github fa-2x" aria-hidden="true"></i> 
			<span>Log In With Github</span>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amura Assignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= 'home-background' if !logged_in? %>">   
    <%= render 'shared/navbar' if logged_in? %>
    <div class="container">
      <%= render 'shared/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/repositories/index.html.erb
<div class="row repo-commits">
	<div class="col-md-12">
		<h1>Repositories</h1>
		<table id="example" class="table table-striped table-bordered nowrap">
			<thead>
				<tr>
					<th>Name</th>
					<th>Open issues</th>
					<th>Stars</th>
					<th>Forks</th>			
					<th>Type</th>
				</tr>
			</thead>
			<tbody>		
				<% if @repositories.present? %>			
					<% @repositories.each do |repo| %>
						<tr>
							<td>
								<%= link_to repo[:name], repository_path(repo[:name]) %>
							</td>
							<td><%= repo[:open_issues] %></td>
							<td><%= number_to_human(repo[:stargazers_count], :format => '%n%u', :units => { :thousand => 'k' }) %></td>
							<td><%= number_to_human(repo[:forks], :format => '%n%u', :units => { :thousand => 'k' }) %></td>
							<td><%= repo[:private] ? 'Private' : 'Public' %></td>
						</tr>
					<% end %>
				<% else %>
					<tr>
						<td colspan="5" class="text-center">
							Not found any repository
						</td>
					</tr>
				<% end %>		
			</tbody>
		</table>
	</div>
</div>

app/views/repositories/show.html.erb
<!-- load the d3.js library -->    
<script src="https://d3js.org/d3.v3.min.js"></script>
<script src="https://labratrevenge.com/d3-tip/javascripts/d3.tip.v0.6.3.js"></script>

<div class="row repo-commits">
	<div class="col-md-8">
		<h3> <%= @repo[:name]%> </h3>
	</div>
	<div class="col-md-4 text-right">
		<%= link_to "Repositories", repositories_path %>
	</div>
	<div class="col-md-12">
		<hr/>
		<p><%= @repo[:description] %></p>
	</div>
</div>

<br/>
<div class="card">
	<div class="card-header">Commits History Graph</div>
	<div class="card-body">
		<div class="row">
			<div class="col-md-3">
				<label> Select commits history date range </label>
			</div>
			<div class="col-md-9">
				<input type="text" name="daterange" value="<%= @since_date.strftime("%m/%d/%Y") %> - <%= @until_date.strftime("%m/%d/%Y") %>" class="form-control" />
			</div>
		</div>
		<br/><br/>
		<div class="row">
			<div class="col-sm-12">
				<!-- Image loader -->
				<div id='loader' style='display: none;' class="text-center">
					<%= image_tag 'reload.gif', size: '300x200' %>
				</div>
				<!-- Image loader -->
				<div class="err text-center"></div>
				<div id="d3_commits_graph"></div>
			</div>
		</div>	
	</div> 
</div>


<script>
	$(function() {
		repo_name = "<%= params[:id] %>";
		start_date = "<%= @since_date.strftime("%Y-%m-%d") %>";
		end_date = "<%= @until_date.strftime("%Y-%m-%d") %>";
		$('input[name="daterange"]').daterangepicker({
			locale: {
				format: 'yy-mm-dd'
			}
		}, function(start, end, label) {
			start_date = start.format('YYYY-MM-DD');
			end_date = end.format('YYYY-MM-DD');
			getCommitsHistory(start_date, end_date, repo_name);
		});
		getCommitsHistory(start_date, end_date, repo_name);
	});
</script>

app/views/shared/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <% if name.to_s == 'notice' %>
          <div class='alert fade-alert alert-success  notice_flash'>
            <button class='close' data-dismiss= 'alert' aria-hidden = 'true' title= <%=I18n.t('global.controls.dismiss')%>>
              &times;
            </button>
            <div id="flash_#{name}">
              <%= msg.html_safe %>
            </div>
          </div>
        <% elsif name.to_s == 'alert' %>
          <div class='alert .fade-alert alert-danger  alert_flash'>
            <button class='close' data-dismiss= 'alert' aria-hidden = 'true' title= <%=I18n.t('global.controls.dismiss')%>>
              &times;
            </button>
            <div id="flash_#{name}">
              <%= msg.html_safe %>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>        
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container">
    <%= link_to repositories_path, class: 'navbar-brand' do %>
      <%= image_tag(current_user.avatar_url, size: '30x30', class: "d-inline-block align-top") %>
      <%= current_user.name %>
    <% end %>
    <div class="navbar-nav">
      <%= link_to "Logout", logout_path, method: :delete, class: "nav-item nav-link pull-right" %>
    </div>
  </div>
</nav>